
// // for(let i = 0; i <= 5; i++){
// //     if(i==2){
// //         continue;
// //     }
// //     if(i===3){
// //         break;
// //     }
    
// //     console.log(i)
// // }
// // let num = 10
// // let str = 'hello'
// // let arr = [1,2,3]
// // let obj = {name:"robin", age:10};
// // let e = null
// // let iosk = true
// // console.log(typeof num)
// // console.log(typeof str)
// // console.log(typeof arr)
// // console.log(typeof e)
// // console.log(typeof iosk)
// // Function definition
// // function Name() {
// //   console.log("Hello my name is Puspendar");
// // }

// // Name();
// //  function add(a,b){
// //     return a + b
// //  }
// //  console.log(add())   
// // let arr = [1,2,3,4,5,6]
// // for(let i = 0; i < arr.length;i++){
// //    if(arr[i] % 2 == 0){
// //       console.log(arr[i])
// //    }
// // }

// // const person = {
// //    key:"hello"}
// //    console.log(person.key)

// // const arr = ["html", " css", "js"];
// // arr.push("python")
// // console.log(arr[3])
// // const sales = "toyota"

// // function carType(name){
// //    return name === "honda"? name:"soryy we dont sell this car"
// // }
// // const car = { carn:" city", getcar: carType("honda"), special: sales
// // }
// // console.log(car.carn)
// // console.log(car.getcar)
// // console.log(car.special)

// const color = ["red", "black", "blue"]
// color.forEach((i) => console.log(i))
// let arr = [1,2,3,4]
// arr.forEach((i,a) => console.log(i+3,a))
// // {
// //    arr[i] +=3
// // }
// // console.log(arr)

// for(const i in color){
//    console.log(i, color[i])
// }
// const user = {name:"robin",age : 25, hobby: "coding"}
// for(const index in user){
//    console.log(index,user[index])
// }



// npx create-react-app MYfirstApp

// npx create vite@latest